### PR TITLE
DownloderUtil

### PR DESCRIPTION
**Pull request by Arashvscode**
There was not enough downloader in this collection, so I created it for you. It is very easy to use and we can confidently say that it is a good alternative to Prd Download.

### CODE REVIEW

**Comment by Arashvscode** [comment]
I will improve this big library as much as I can, with the help of God and all my friends, this downloader has been tested on a sk pro project and it works well, just don't tamper with the codes if you don't have enough knowledge.

**Comment by abodinagdat16** [comment]
@Arashvscode do not use NotificationCompat  use NotificationUtils.... delete R.drawable.....

**Comment by Arashvscode** [comment]
> 
  OK, I will fix it soon

**Comment by abodinagdat16** [comment]
@Arashvscode use android Notification don't use NotificationCompat

**Comment by arab-ware** [comment]
Amazing work but can you do slowly I mean no need to be fast , so you can make it with no bug or error

Thank you for helping people by developing Utils in this library

**Comment by Arashvscode** [comment]
> Amazing work but can you do slowly I mean no need to be fast , so you can make it with no bug or error
> 
> Thank you for helping people by developing Utils in this library

If you like you can make your own. This little bug is under my laptop ruined today and have laptops in the hand

**Pull request merged**
